### ISSUE TITLE
交叉编译到 armv7 报错

### ISSUE THREAD

**Issue by dammu** [ystyle/kas#1]
好像是 int 溢出了，这咋办
```
# github.com/ystyle/kas/util/file
util/file/bytesFormat.go:10:19: constant 1099511627776 overflows int
util/file/bytesFormat.go:13:36: constant 1099511627776 overflows int
```

**Comment by ystyle** [comment]
这个错好解决，你把G和T的format删掉，把m的改为else。 就能编译通过了。
但真正的问题是kindlegen，不支持arm平台，编译了也只有txt转epub功能可用。

而且kindlegen这玩意官方不维护了，以后这东西也可能没什么用了（具体什么时候kindle会改格式就不知道了）。。。

**Comment by dammu** [comment]
> 这个错好解决，你把G和T的format删掉，把m的改为else。 就能编译通过了。
> 但真正的问题是kindlegen，不支持arm平台，编译了也只有txt转epub功能可用。
> 
> 而且kindlegen这玩意官方不维护了，以后这东西也可能没什么用了（具体什么时候kindle会改格式就不知道了）。。。

这个错解决了。但是交叉编译出来的文件放上去 `./kas-arm`却会报错，编译命令是参照 build.sh 改的，但是运行报错：
```
panic: could not locate box "public"

goroutine 1 [running]:
github.com/GeertJohan/go%2erice.MustFindBox(...)
	/home/dammu/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.0/box.go:110
main.main()
	/home/dammu/kas/main.go:72 +0xb08
```
最后我就下了个官网的 armv6l 的 golang 包用`go run main.go`了，可以的话还是想知道这是为什么，能不能，如何解决（虽然暂时是能用 go run 用上）

**Comment by ystyle** [comment]
### 编译
```shell
# git bash下执行的命令
$ go version
go version go1.13.7 windows/amd64
$ GOOS=linux GOARCH=arm go build  -o kas-linux-ARM main.go # 交叉编译
$ rice append --exec kas-linux-ARM # 用rice绑定资源文件
```
>rice用法可以看官方文档: https://github.com/GeertJohan/go.rice#tool-usage
>我编译是没问题的，你估计是安装的rice没弄好，你按官方文档操作一下，我自己是用append方式添加的(看编译后的命令)

### 在树莓派上执行
```
[alarm@alarmpi Download]$ ./kas-linux-ARM 
{"time":"2020-09-28T00:22:51.434781682+08:00","level":"ERROR","prefix":"-","file":"util.go","line":"32","message":"open asset/website_list.json: file does not exist"}

   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v3.3.10-dev
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on [::]:1323

```
>~~日志那行website_list的不影响，原因是下面说的文章下载是个半成品，大部分文章下载不了，可有可无的东西。。~~
>经测试应该是rice不支持arm, 所以网页版也用不了了

### 另外
1. txt转epub
2. txt转mobi
3. 下载hcomic漫画(kaf或网页版)
4. 下载文章

arm 平台的话，目前只有1的功能可以用，其它用不了。原因是[kindlegen](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211)没arm平台的
