### ISSUE TITLE
怎么在arm设备上搭建呢

### ISSUE THREAD

**Issue by endandleaf** [ystyle/kas#3]
1M速度太慢了，有个armbian，怎么在上面搭建呢

**Comment by ystyle** [comment]
arm上不支持mobi格式

如果里边有docker的话，直接`docker build -t ystyle/kas .` 应该就能build出来，然后运行
```shell
docker run -d --name hcc \
 --restart always \
 -p 1323:1323 \
 -v /mnt/kas/storage:/app/storage \
  ystyle/kas
```

手工编译的话，要先安装好go， 配置好gobin
```shell
go get github.com/GeertJohan/go.rice
go get github.com/GeertJohan/go.rice/rice
GOOS=linux GOOS=arm64 go build -ldflags "-s -w" -o kas-linux main.go
rice append --exec kas-linux
```

**Comment by endandleaf** [comment]
我试一下，kindle马上要不支持Mobi了

**Comment by endandleaf** [comment]
不行，显示不匹配。  The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by ystyle** [comment]
你是用docker的还是手工编译的？

**Comment by endandleaf** [comment]
> arm上不支持mobi格式
> 
> 如果里边有docker的话，`docker build -t ystyle/kas .`直接应该构建出来，然后运行
> 
> ```shell
> docker run -d --name hcc \
>  --总是重启\
>  -p 1323:1323\
>  -v /mnt/kas/storage:/app/storage \
>   ystyle/kas
> ```
> 
> 手工编译的话，要先安装好go，配置好gobin
> 
> ```shell
> 去获取 github.com/GeertJohan/go.rice
> 去获取 github.com/GeertJohan/go.rice/rice
> GOOS=linux GOOS=arm64 go build -ldflags " -s -w " -o kas-linux main.go
> 大米追加--exec kas-linux
> ```

**Comment by endandleaf** [comment]
docker的

**Comment by ystyle** [comment]
docker 上有arm64版本的了， 直接用 ystyle/kas:latest 标签就好了

**Comment by endandleaf** [comment]
感谢，我试一下

**Comment by endandleaf** [comment]
拉取不了

Failed to pull manifest by the resolved digest. This registry does not
	appear to conform to the distribution registry specification; falling back to
	pull by tag.  This fallback is DEPRECATED, and will be removed in a future
	release.  Please contact admins of https://mirror.baidubce.com/.

**Comment by endandleaf** [comment]
重新拉取了一下，部署成功了，非常感谢！！！！
